In [5]:
import requests
response = requests.get('https://api.escuelajs.co/api/v1/products/17')
response.json()

{'id': 17,
 'title': 'Classic Black T-Shirt ',
 'slug': 'classic-black-t-shirt',
 'price': 34,
 'description': "Elevate your everyday style with our Classic Black T-Shirt. This staple piece is crafted from soft, breathable cotton for all-day comfort. Its versatile design features a classic crew neck and short sleeves, making it perfect for layering or wearing on its own. Durable and easy to care for, it's sure to become a favorite in your wardrobe.",
 'category': {'id': 1,
  'name': 'T-Shirts',
  'slug': 't-shirts',
  'image': 'https://i.imgur.com/QkIa5tT.jpeg',
  'creationAt': '2026-04-08T19:37:19.000Z',
  'updatedAt': '2026-04-09T14:02:11.000Z'},
 'images': ['https://i.imgur.com/9DqEOV5.jpeg',
  'https://i.imgur.com/ae0AEYn.jpeg',
  'https://i.imgur.com/mZ4rUjj.jpeg'],
 'creationAt': '2026-04-08T19:37:19.000Z',
 'updatedAt': '2026-04-09T14:31:42.000Z'}

In [ ]:
#GET para visualizar productos

url = "https://api.escuelajs.co/api/v1/products"
response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)
df.head()

,id,title,slug,price,description,category,images,creationAt,updatedAt
0,17,Classic Black T-Shirt,classic-black-t-shirt,34,Elevate your everyday style with our Classic B...,"{'id': 1, 'name': 'T-Shirts', 'slug': 't-shirt...","[https://i.imgur.com/9DqEOV5.jpeg, https://i.i...",2026-04-08T19:37:19.000Z,2026-04-09T14:31:42.000Z
1,19,Sleek Wireless Headphone & Inked Earbud Set,sleek-wireless-headphone-inked-earbud-set,44,Experience the fusion of style and sound with ...,"{'id': 2, 'name': 'Electronics', 'slug': 'elec...","[https://i.imgur.com/yVeIeDa.jpeg, https://i.i...",2026-04-08T19:37:19.000Z,2026-04-08T19:37:19.000Z
2,20,Sleek Comfort-Fit Over-Ear Headphones,sleek-comfort-fit-over-ear-headphones,28,Experience superior sound quality with our Sle...,"{'id': 2, 'name': 'Electronics', 'slug': 'elec...","[https://i.imgur.com/SolkFEB.jpeg, https://i.i...",2026-04-08T19:37:19.000Z,2026-04-08T19:37:19.000Z
3,21,Efficient 2-Slice Toaster,efficient-2-slice-toaster,48,Enhance your morning routine with our sleek 2-...,"{'id': 2, 'name': 'Electronics', 'slug': 'elec...","[https://i.imgur.com/keVCVIa.jpeg, https://i.i...",2026-04-08T19:37:19.000Z,2026-04-08T19:37:19.000Z
4,22,Sleek Wireless Computer Mouse,sleek-wireless-computer-mouse,10,Experience smooth and precise navigation with ...,"{'id': 2, 'name': 'Electronics', 'slug': 'elec...","[https://i.imgur.com/w3Y8NwQ.jpeg, https://i.i...",2026-04-08T19:37:19.000Z,2026-04-08T19:37:19.000Z

In [15]:
#POST para crear un producto nuevo

url = "https://api.escuelajs.co/api/v1/products/"

nuevo_producto = {
    "title": "Buzo rojo",
    "price": 120000,
    "description": "Buzo rojo creado desde python",
    "categoryId": 1,
    "images": ["https://placeimg.com/640/480/any"]
}

response = requests.post(url, json=nuevo_producto)

data_post = response.json()

df_post = pd.DataFrame([data_post])
df_post

,id,title,slug,price,description,category,images,creationAt,updatedAt
0,327,Buzo rojo,buzo-rojo,120000,Buzo rojo creado desde python,"{'id': 1, 'name': 'T-Shirts', 'slug': 't-shirt...",[https://placeimg.com/640/480/any],2026-04-09T15:43:06.000Z,2026-04-09T15:43:06.000Z